"""Initial models

Revision ID: 008d13b9f78b
Revises: 
Create Date: 2025-12-04 13:45:56.887976

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '008d13b9f78b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('battle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('college_a', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('college_b', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('score_a', sa.Integer(), nullable=False),
    sa.Column('score_b', sa.Integer(), nullable=False),
    sa.Column('winner', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('battleparticipant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('battle_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('bet_amount', sa.Integer(), nullable=False),
    sa.Column('reward_amount', sa.Integer(), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('carbonlog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('log_date', sa.Date(), nullable=False),
    sa.Column('transport_km', sa.Float(), nullable=False),
    sa.Column('cup_count', sa.Integer(), nullable=False),
    sa.Column('ac_hours', sa.Float(), nullable=False),
    sa.Column('total_emission', sa.Float(), nullable=False),
    sa.Column('ai_feedback', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('challenge',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('goal_value', sa.Integer(), nullable=False),
    sa.Column('reward_points', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('challengeprogress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('challenge_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('current_value', sa.Integer(), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mileagerequest',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('request_points', sa.Integer(), nullable=False),
    sa.Column('converted_mileage', sa.Integer(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('college', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('current_points', sa.Integer(), nullable=False),
    sa.Column('avatar_status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('mileagerequest')
    op.drop_table('challengeprogress')
    op.drop_table('challenge')
    op.drop_table('carbonlog')
    op.drop_table('battleparticipant')
    op.drop_table('battle')
    # ### end Alembic commands ###
