"""empty message

Revision ID: 372c5ecb03e8
Revises: 008d13b9f78b
Create Date: 2025-12-05 16:39:50.617061

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '372c5ecb03e8'
down_revision: Union[str, Sequence[str], None] = '008d13b9f78b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('carbonlog', schema=None) as batch_op:
        batch_op.add_column(sa.Column('activities_json', sqlmodel.sql.sqltypes.AutoString(), server_default=sa.text("'[]'"), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('carbonlog', schema=None) as batch_op:
        batch_op.drop_column('activities_json')

    # ### end Alembic commands ###
