"""init models

Revision ID: 49d258bdc972
Revises: 372c5ecb03e8
Create Date: 2025-12-09 18:44:33.609497

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '49d258bdc972'
down_revision: Union[str, Sequence[str], None] = '372c5ecb03e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('carbonlog', schema=None) as batch_op:
        batch_op.add_column(sa.Column('points_earned', sa.Integer(), server_default=sa.text('0'), nullable=False))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('avatar_status')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar_status', sa.VARCHAR(), nullable=False))

    with op.batch_alter_table('carbonlog', schema=None) as batch_op:
        batch_op.drop_column('points_earned')

    # ### end Alembic commands ###
