"""add source column to carbonlog

Revision ID: a1b2c3d4e5f6
Revises: 5d43171a93f4
Create Date: 2025-12-12 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'a1b2c3d4e5f6'
down_revision: Union[str, Sequence[str], None] = '5d43171a93f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('carbonlog', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source', sa.VARCHAR(), server_default='carbon_input', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('carbonlog', schema=None) as batch_op:
        batch_op.drop_column('source')

    # ### end Alembic commands ###
